### ISSUE TITLE
Step_filter_missing enhancements

### ISSUE THREAD

**Issue by nhward** [tidymodels/recipes#1035]
Regarding `step_filter_missing()`: This is a great addition but the name implies it is removing rows rather than columns. Compare with `step_filter()`. Perhaps a different name? `step_excess_missing()`?

**Can I suggest a related feature enhancement?** If the function has both a variable missingness threshold AND an observation missingness threshold then both rows and columns can be removed. Since the order of doing these should always be 
1. variables first, 
2. observations second, 
to ensure the maximum number of observations are always retained. Having these two operations in a single recipe step ensures the order is optimal. 

I find that, depending on the quality of imputation, varying the value for the observation missingness threshold allows the model's performance metric to be optimised. I hope you are following my thinking. 

Keep up the good work. I am a fan of **recipes**.

**Comment by EmilHvitfeldt** [comment]
Hello @nhward 👋  Thanks for opening an issue!

We do agree that the name for this step isn't the best considering the use of the work `filter`, however it was the best shortest solution we were able to find when we wrote it.

At the moment we are wary of adding many more methods of of removing observations as it leads to problems if not done carefully https://github.com/tidymodels/recipes/issues/943. I don't think this should make its way into recipes.

If you are planning to remove observations due to data quality (e.i. to high missing % within an observation) I would recommend that you do that to the data before you use it in a recipe 😄

**Comment by nhward** [comment]
Two points to make in defence of the idea:

1) Consider the following scenario:
Observations that are more than 50% missing are considered poor quality cases (even after imputation). Suppose I clean these out of both train and test sets, build a model and deploy it. There is nothing causing future cases of low quality to be rejected, as I would want. This behaviour would need to be manually coded outside of the model and its recipe. In contrast if this is managed by a recipe (in which the **skip** parameter can be T or F) the behaviour on future cases can be managed appropriately.  In short, there is value in dropping observations using recipes.

2) Your recipe step that removes excessively missing variables is best when it comes before the removal of excessively missing observations (as this order maximises the retained row count). Yet you recommend that the removal of excessively missing observations to be done before the data reaches a recipe. Given the order that works best, the behaviour of step_filter_missing() should also need to be done before the data reaches a recipe (but before observation missingness is resolved.) If anyone is interested in both processes, they cannot use `set_filter_missing()` as a recipe step.

Please reconsider. 
`step_filter()` and `step_naomit()` are precedence examples of utility over caution.
