### ISSUE TITLE
LabelEncoder-like functionality

### ISSUE THREAD

**Issue by Hisham-Hussein** [tidymodels/recipes#123]
Hi Max, and thanks for the great package. 

I watched your interesting presentation titled (I don't want to be a dummy), and actually based on my experience, I tend to find that label_encoding of categorical variables is generally better than one_hot (dummy variables) encoding, in terms of training speed as well as robustness to overfitting. 

So my question is: is there a function that transforms a categorical variable to numeric representation (like the LabelEncoder class in scikit-learn), plus handling novel levels in the test data?

That would be very nice to have! 

Thank you in advance

**Comment by topepo** [comment]
Something like this:
```r
> LabelEncoder <- function(x) {
+   as.numeric(x) - 1
+ }
> 
> test <- iris$Species[c(1:2, 51:52, 100:101)]
> test
[1] setosa     setosa     versicolor versicolor versicolor virginica 
Levels: setosa versicolor virginica
> LabelEncoder(test)
[1] 0 0 1 1 1 2
```
We generally eschew this way of representing qualitative data. It wouldn't be much trouble to ad this though. 

I think that the `tensorflow` and/or `keras` packages might have built-in functions for doing this.

**Comment by Hisham-Hussein** [comment]
Thanks for your reply Max.. 

yes this works in a basic way. But I was asking for a more sophisticated implementation:

- LabelEncoder is a kind of estimator class that fits the training data and remembers the levels it saw
- Then it transforms the training data
- Then it transforms the testing data, provided that the test data is not known in advance, so it should has a built-in functionality to deal with novel levels in the test data (which is encountered frequently in the real world)
- For example, once it sees novel levels in the test data ---> replace it with an arbitrary number the user chooses when fitting the transformer (and if he didn't specify that number, use NAs for the novel levels)

Also: 
I'm curious to know why this way of representing qualitative data is not preferred? 
Given that in your talk I saw that it led to either the same or better results than one-hot encoding, and in terms of training speed it was almost always better. 

Also I've tried both representations (LabelEncoder and one-hot) many times in my work and in kaggle competitions and always find the one-hot encoding slower as well as more prone to overfitting, especially when using tree-based algorithms, especially xgboost

Could you please elaborate on this point? I'd like to learn from your experience as well

Thanks again Max,

Kind Regards,
Hisham

**Comment by topepo** [comment]
> Then it transforms the testing data, provided that the test data is not known in advance, so it should has a built-in functionality to deal with novel levels in the test data (which is encountered frequently in the real world)

So does it increase the number of integers for the new level or drop that level into an existing slot? We are adding a feature hashing step (although I find that approach enormously unsatisfying from a statistical perspective). 

> I'm curious to know why this way of representing qualitative data is not preferred?

(the following rant is largely about _unordered_ qualitative data)

I want to separate how we _store_ qualitative data from how we _represent it_ for our purposes. I think conflating the two (as integer values would) is bad. 

Since R has a wonderful method for storing and summarizing qualitative data (factors), we don't have to take a low-level approach of encoding them as some type of number(s). For example, using `table(factor_var)` is much better than `table(integer_var)` because

* The factor has memory of the levels. An integer vector would need to have a definition for what the maximum number of integers would be so that it can put zeros in the table for levels that are possible but not observed.  
 
* For both aesthetic and content reasons, showing the _actual_ levels is far better for communicating values. 

and so on. 

Also, there is the not-so-far-fetched issue of people doing computations on the numbers that treat an integer value of 2 is twice the value of the integer value of the first level. For neophytes, this can happen easily and they might not be aware of it. 

I could ramble on (and have in the past) but basically I feel that you should keep the best representation of the data until you absolutely need to encode it numerically. I have a hard time figuring out a case where some indicator variable encoding is inferior to an integer representation. An integer representation is probably a construct of how the implementation is written and that would be the "tail wagging the dog."

In `recipes`, `step_ordinalscore` does something similar to what you are interested in but it is only for ordered factors (where it makes sense to do this) and wouldn't know what to do with new values. 

I'll take a look at `CatEncoders` too.

**Comment by lorenzwalthert** [comment]
On a related note: https://github.com/bfgray3/cattonum/issues/20

**Comment by kevinykuo** [comment]
Keras embedding layer requires that categorical variables be encoded as 0-based integer arrays. It doesn't seem like https://github.com/tidymodels/recipes/commit/cf2e5e6634d5569ec32b16b7fa7b17903395f1b8 can do that since `0` is reserved for unseen labels?

**Comment by topepo** [comment]
I thought that was the convention for `layer_embed`; zero values corresponded to potentially new values.

**Comment by kevinykuo** [comment]
Here's the documentation for `layers.Embedding`: https://keras.io/layers/embeddings/. It doesn't seem like it has support for handling unseen data built in. `mask_zero` can be used if you have recurrent layers down the line, but it's not turned on by default anyway.

**Comment by topepo** [comment]
I was following [this guide](http://flovv.github.io/Embeddings_with_keras/) which uses 

> The first layer is the embedding layer with the size of 7 weekdays plus 1 (for the unknowns).

and then
```r
embeddings$name <- c("none", levels(wday(df$date, label = T)) )
```
to make the first level of the factor apart from the actual factor levels. 

Maybe @skeydan would have more info...

**Comment by kevinykuo** [comment]
The use case I'm mostly concerned about is using the embedding layer with a categorical variable in a structured data setting. What we're discussing is whether a categorical variable should be processed to be a 0- or 1- based vector. E.g. should `iris$Species` be encoded as `0, 0, ..., 1, 1, ..., 2, 2` or `1, 1, ..., 2, 2, ..., 3, 3`.

**Comment by topepo** [comment]
I can modify it to be zero-based (as an option) but would throw errors if a new value is encountered. 😩

**Comment by skeydan** [comment]
My best guess ... I think it does not matter so much.... the way I understand the docs it means that per default, 0 can be a value like any other (if you leave mask_zero at its default of false)...

However if you just don’t use it, it would be like a mysterious value that never appears, but not change the results much...

So my guess would be starting from 1 could work just fine... but one could also do a quick test with simulated data to find out....

**Comment by kevinykuo** [comment]
Throwing an exception may be desirable in some cases, e.g. when you know you shouldn't have unseen labels. We can have a parameter that controls the behavior. FWIW Spark has a parameter `handleInvalid` that defaults to "error" when it sees unseen labels or missings.

It feels weird to me to have to set your input dim to number of classes + 1, when you know that you won't have new levels.

**Comment by topepo** [comment]
> It feels weird to me to have to set your input dim to number of classes + 1, when you know that you won't have new levels.

But we don't know that and accommodating novel levels has been a consistent request.

**Comment by kevinykuo** [comment]
Agreed we should support accommodating novel levels (by default), but would you be OK with adding a parameter to allow 0-based indexing and we can document that it'll puke on unseen labels? Or maybe lump novel levels to code `num_classes` in that case, since the known levels go from `0` to `num_classes - 1`? This way, `input_dim` can still correspond to number of classes, and the user won't notice the difference. If the user does encounter novel levels, Keras will throw an index out of bounds exception, which will be informative.

**Comment by topepo** [comment]
That's a good idea. I'll get to it in a few days

**Comment by skeydan** [comment]
Last night I was typing on the i-pad so probably it was not too intellegible (plus, no code) ... what I was trying to say was that I'd suspect it makes no semantic difference (to keras).
Now reading the recent comments I think that goes well with this:

>  Or maybe lump novel levels to code num_classes in that case, since the known levels go from 0 to num_classes - 1

Also reg. this

> If the user does encounter novel levels, Keras will throw an index out of bounds exception, which will be informative.

I think that's a good idea, because in some way, the user just needs to take care of this, otherwise embeddings make no sense.

I've extracted some test code (slightly adapted, e.g., using 2d embeddings for direct viz) from the post you mentioned, so one can compare two versions and see how the weekdays get mapped.

First, the original way, weekdays go from 1-7 and input_dim is set to 8:

```
#https://www.kaggle.com/new-york-city/nyc-east-river-bicycle-crossings
library(dplyr)
library(keras)
library(lubridate)
library(ggplot2)

use_session_with_seed(7777,
                      disable_gpu = FALSE,
                      disable_parallel_cpu = FALSE)

df <- read.csv("nyc-east-river-bicycle-counts.csv")
df %>% glimpse()
df$date <- as.Date(df$Date)
df$weekday <- lubridate::wday(df$date)

###
#df$weekday <- df$weekday - 1
###

###
input_dim <- 8
# input_dim <- 8
###

df$users <- df$Brooklyn.Bridge

df <- df[df$users > 0, ]
df <- df[!is.na(df$users), ]
df <- df[!is.na(df$weekday), ]

df$ScaledUsers <- scale(df$users)

embedding_size <- 2

model <- keras_model_sequential()

model %>% layer_embedding(
  input_dim = input_dim,
  output_dim = embedding_size,
  input_length = 1,
  name = "embedding"
) %>%
  layer_flatten()  %>%
  layer_dense(units = 40, activation = "relu") %>%
  layer_dense(units = 10, activation = "relu") %>%
  layer_dense(units = 1)

model %>% compile(loss = "mse",
                  optimizer = "adam",
                  metric = "mse")

hist <-
  model %>% fit(
    x = as.matrix(df$weekday),
    y = as.matrix(df$ScaledUsers),
    epochs = 50,
    batch_size = 10
  )

layer <- get_layer(model, "embedding")


embeddings <- data.frame(layer$get_weights()[[1]])

###
embeddings$name <- c("none", levels(wday(df$date, label = T)))
#embeddings$name <- levels(wday(df$date, label = T))
###

ggplot(embeddings, aes(X1, X2, color = name)) + geom_point() + geom_text(aes(label =
                                                                               name), hjust = 0, vjust = 0) + theme_bw() + xlab("Embedding Dimension 1") +
  ylab("Embedding Dimension 2")
```

And here's the second, with weekdays going from 0-7:

```
#https://www.kaggle.com/new-york-city/nyc-east-river-bicycle-crossings
library(dplyr)
library(keras)
library(lubridate)
library(ggplot2)

use_session_with_seed(7777,
                      disable_gpu = FALSE,
                      disable_parallel_cpu = FALSE)

df <- read.csv("nyc-east-river-bicycle-counts.csv")
df %>% glimpse()
df$date <- as.Date(df$Date)
df$weekday <- lubridate::wday(df$date)

###
df$weekday <- df$weekday - 1
###

###
input_dim <- 7
# input_dim <- 8
###

df$users <- df$Brooklyn.Bridge

df <- df[df$users > 0, ]
df <- df[!is.na(df$users), ]
df <- df[!is.na(df$weekday), ]

df$ScaledUsers <- scale(df$users)

embedding_size <- 2

model <- keras_model_sequential()

model %>% layer_embedding(
  input_dim = input_dim,
  output_dim = embedding_size,
  input_length = 1,
  name = "embedding"
) %>%
  layer_flatten()  %>%
  layer_dense(units = 40, activation = "relu") %>%
  layer_dense(units = 10, activation = "relu") %>%
  layer_dense(units = 1)

model %>% compile(loss = "mse",
                  optimizer = "adam",
                  metric = "mse")

hist <-
  model %>% fit(
    x = as.matrix(df$weekday),
    y = as.matrix(df$ScaledUsers),
    epochs = 50,
    batch_size = 10
  )

layer <- get_layer(model, "embedding")


embeddings <- data.frame(layer$get_weights()[[1]])

###
# embeddings$name <- c("none", levels(wday(df$date, label = T)))
embeddings$name <- levels(wday(df$date, label = T))
###

ggplot(embeddings, aes(X1, X2, color = name)) + geom_point() + geom_text(aes(label =
                                                                               name), hjust = 0, vjust = 0) + theme_bw() + xlab("Embedding Dimension 1") +
  ylab("Embedding Dimension 2")
```

Now ... learning curves are very similar in both cases, but the embeddings aren't ... :-( 

Here's the first:

![image](https://user-images.githubusercontent.com/469371/45472566-db495a00-b734-11e8-9844-d07a90953463.png)

And the second:

![image](https://user-images.githubusercontent.com/469371/45472458-932a3780-b734-11e8-9cae-c127ee0d8b0b.png)


It's clear that the embeddings can't be the same exactly as the matrices are different sizes, but this pretty different... 
What do you think? Do you see an obvious mistake in my comparison code?
If not, I could look into the code as anyway, I might be doing a post on embeddings some time soon...

**Comment by skeydan** [comment]
Okay, from the code - they always say an embedding is nothing but a lookup and really it is:

```
def call(self, inputs):
        if K.dtype(inputs) != 'int32':
            inputs = K.cast(inputs, 'int32')
        out = K.gather(self.embeddings, inputs)
return out
```

All `k.gather` does is lookup indices in a tensor:

```
Description
Retrieves the elements of indices indices in the tensor reference.

Usage
k_gather(reference, indices)
```

So then to me that would mean that from the user's point of view, all that matters is that they get the thing they want ... 
Say my data are 0-based. I pass in a 0. Now  keras will look up the 0th vector (column/row, whatever), no matter if that was Sunday or Monday or ... 
And so on.

This would also mean that I could just as well have my integers going from 777 to 777+7 ... 

Keras will just complain if there are too many values. I didn't test, but the +1 in `num_classes + 1` only seems to apply when we do something with `mask_zero` - see my 2nd snippet above, I have 7 weekdays ranging from 1 to 7 & my input_dim is 7. And it works.

So this is how I understand the mechanics - do you agree?

Now what does this mean for unknown values (which for keras is not a relevant concept)?
I would say it doesn't matter what you map them to - say 0, or say the value at `max + 1` - as long as you make sure you set `input_shape` correctly.
Am I right?

**Comment by skeydan** [comment]
Okay, I just found out this is also release-dependent 

For this setup 

```
> n_users
[1] 671
> ratings$userId %>% min()
[1] 1
> ratings$userId %>% max()
[1] 671
```

I can have `input_dim` = 671 with TF 1.10 and 1.11, but not TF1.12:

```
  InvalidArgumentError: indices[14] = 671 is not in [0, 671)
	 [[{{node user_embedding/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@training/Adam/Assign_2"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](user_embedding/embeddings/read, user_embedding/Cast, training/Adam/gradients/user_embedding/embedding_lookup_grad/concat/axis)]]


```

**Comment by lorenzwalthert** [comment]
Sorry just to double check (and spoil the thread): Can I use one-based indexing in keras for embeddings or am I supposed to use zero-based indexing? If yes, maybe the doc / help file should be adapted there? @skeydan

**Comment by topepo** [comment]
Try it now to see if that helps with zero-based integers
