### ISSUE TITLE
step_nzv can create surprises downstream

### ISSUE THREAD

**Issue by michaellevy** [tidymodels/recipes#140]
When using `recipes` programmatically, we might not know what columns `step_nzv` will remove. If it removes all nominal columns and there's a step for nominals downstream, it breaks. A general solution that would make the package more flexible would be to let prepping go through even if no columns are selected, and just have the step not do anything. I'd be happy to work on that if you want.

``` r
library(recipes)
d <- data.frame(x = c(rep("a", 29), 'B'), y = rnorm(30))
recipe(d, y ~ x) %>%
  step_nzv(all_nominal()) %>%
  step_dummy(all_nominal()) %>%
  prep(d)
#> Error: No variables or terms were selected.
```

Created on 2018-03-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by topepo** [comment]
Good idea but keep in mind that this would have to affect every step and check. `abort_selection` could be changed to `warn_empty_selection` and each step would need a test to make sure there is no error when nothing is selected. 

Also, we would need `prep` to throw an error (maybe?) if all the variables in the entire data set are excluded (or return an empty tibble).

**Comment by alexpghayes** [comment]
I'm in favor of throwing an error. Models shouldn't fit on empty datasets and who knows who good the error checking will be downstream.

**Comment by topepo** [comment]
@michaellevy Any ideas other than a more informative error message?

**Comment by topepo** [comment]
@michaellevy 

So maybe there are two different issues here:

 1. What happens if a step that filters variables removes everything in the data set?
 2. What do you do in any step when the selectors don't select any variables to process? 

My first read on this was about the first point but

> let prepping go through even if no columns are selected, and just have the step not do anything.

That sounds more about the second point. 

I think that, for the first, we should halt execution if the tibble has no columns. 

For the second, we could write some logic into the steps (individually) that would just disregard any computations in that step. So suppose you want to do PCA but don't select any variables (even though there are columns in the tibble). Should we throw an error or just act like we never ran `step_pca`?

**Comment by tomliptrot** [comment]
@topepo 

on this 

> For the second, we could write some logic into the steps (individually) that would just disregard any computations in that step. So suppose you want to do PCA but don't select any variables (even though there are columns in the tibble). Should we throw an error or just act like we never ran step_pca?

Has any progress been made on this? I am running into an issue when I try to run say `step_modeimpute(all_nominal())` in cases where I'm not sure in advance if there will be any nominals. I've worked around it by adding an `if (any( var_types == 'nominal')){...` filter, but its not very nice. I think in those cases it should just act like that step was never run. I'd be happy to contribute to this with a bit of guidance...

**Comment by topepo** [comment]
We've been looking at this in some detail. The conclusion is that we will want steps to keep going (with a warning) if no columns are selected. There are 2-3 technical issues that we'll need to work on. 

I'll close this issue and start a new one (that references this one) for those changes.
