### ISSUE TITLE
Tibble with outcome

### ISSUE THREAD

**Issue by grayskripko** [tidymodels/recipes#190]
I see some duplications in modeling pipeline when I have to specify outcome with formula or not. 
```
recipe(data, y ~ ., ...)
boost_tree(...) %>% fit(y ~ ., ...)
roc_auc(truth = y, ...)
```

I'm not sure this is a good idea but just wanted to propose it to consider: I find it pretty handy to specify outcome variable one time only. For example:
```
read_csv("abc.csv") %>% 
    set_outcome(y) %>%
    recipe() %>%  # without any arguments here!
    ...
```
or 
```
read_csv("abc.csv") %>% 
    set_outcome(y) %>%
    boost_tree(...) %>% 
    fit(...)  # formula argument is redundant here
    ...
```

Sometimes you don't need ```repice()```, its steps and ```prep()``` at all but will use your tibble in ```parsnip::fit``` and assess its result.
After adding this information to the tibble all ```formula``` and ```truth```arguments could be ignored.

What do you think?

**Comment by topepo** [comment]
I understand you point. Here are some small notes about this:

You could create and prep the recipe once before piping it in to models and you don't have to use the formula method:

```r
recipe(x = iris) %>% 
  add_role(everything()) %>% 
  add_role(Species, new_role = "outcome") %>% 
  summary()
```

Also, the model functions like `boost_tree` don't have any data-related arguments; they are general model specifications. `fit` does but deliberately does not have a recipe method. The reason is that we don't want to have to prepare the recipe multiple times (which is what would happen inside of `fit`). 

However, we are putting together a model [workflow/pipeline](https://github.com/orgs/tidymodels/projects/3) structure that would capture a model specification, filters, etc so that one `fit` call be used to make the whole thing. For the pipeline object, a series of `set_{role}` functions would be a good idea.

**Comment by grayskripko** [comment]
I need to clarify. I meant it is possible to create something like a wrapper over tibble class that will be spat out from 
```
read_csv(...) %>% set_outcome(y) %>% class 
#>  "tbl_outcome_or_like_that" "tbl_df"     "tbl"        "data.frame"
```
and this object will contain information about outcome feature inside (could be attached with a simple ```attr()``` inside of hypothetical ```set_outcome()```). In fact, you don't even need to create a new class and it's possible just to check the presence of this attribute in a bunch of main functions with ```formula``` and ```truth``` functions. But I'm not sure about the last approach without the new class.

Maybe the pipeline will be enough.

**Comment by grayskripko** [comment]
the same idea of the extended tibble 
```
read_csv(...) %>% recipe(y ~ .) %>% step_dummy(...) %>% prep(retain = T) %>% juice() %>% class()
#>  "tbl_outcome_or_like_that" "tbl_df"     "tbl"        "data.frame"
```
By the way, it's sad that this imaginary pipeline is impossible in ```recipes```. You have to break it because ```prep()``` requires you to specify data one more time after you did it in ```recipe()```

**Comment by topepo** [comment]
It can be done, I just think that `set_outcome` is a good idea in that context. 

> `prep()` requires you to specify data one more time after you did it in `recipe()`

That is potentially changeable. If you want, submit another issue about re-using the template with `prep`.
