### ISSUE TITLE
Feature Request: step_meanimpute() enhanchment  

### ISSUE THREAD

**Issue by rczen** [tidymodels/recipes#390]
Hi,
It is possible to extend the step_meanimpute() and step_medianimpute(), to be able and compute a group-specific statistic, by providing a factor variable as an argument.

Suppose I have a dataset which lists income per profession:
it would be much more appropriate to impute rows without income based on the mean or median per profession rather than impute the value solely based on on the variable we would like to impute.

**Comment by topepo** [comment]
We don't have a method for doing that in recipes right now. That would have to happen on a step-by-step basis and gets very complicated. 

Also, I'm skeptical of doing this because it might potentially encourage bad behavior. For example, it would be a bad idea (in most cases) to preprocess the data in a _supervised manner_ (i.e. the grouping variable is the outcome). There are plenty of appropriate use cases too but adding such a feature does concern me. 

In the meantime, you could use `step_bagimpute()` and only give `impute_with` the profession column.

**Comment by rczen** [comment]
Sure, I will give it a try and see if the results coincide.

**Comment by fatih-boyar** [comment]
Hi, I was came upon this same exact issue myself. Thanks for these information, your suggestion seems very convenient.
