### ISSUE TITLE
tidy tools for unsupervised learning methods?

### ISSUE THREAD

**Issue by pstraforelli** [tidymodels/recipes#465]
I discussed this Max during the Applied ML workshop at RStudioConf 2020, and he suggested that I opened an issue about it on this repo. 

I was wondering if there was any appetite in setting up tidy tools for unsupervised learning methods, particularly ensemble methods. The best package I can find on this is the [clue package](https://cran.r-project.org/web/packages/clue/vignettes/clue.pdf). Unfortunately the only documentation about the package is the linked vignette, and I have found it unhelpful in understanding how the workflow is supposed to be implemented to apply a consensual ensemble clustering with a raw data set. 

This is tangentially related to #399, but I wanted at least to initiate a discuss whether there is an interest in going down that path. I often run clustering methods in my work, and I currently use a licensing software ([CCEA by Sawtooth Software](https://www.sawtoothsoftware.com/products/advanced-analytical-tools/ccea)). Being able to keep this work in the R ecosystem, particularly the tidyverse ecosystem, would be huge for me.

**Comment by topepo** [comment]
Most unsupervised operations would happen in a recipe. It might be a bit ungainly but an ensemble method could be a new recipe step. 

I personally think that any step with the name "cluster" in it should yield a qualitative cluster membership column (otherwise call it a centroid step or something). I think using the closest centroid would be fine for non-ensembled clustering methods.

**Comment by pstraforelli** [comment]
Hi Max - just curious about the outcome for this issue?
