### ISSUE TITLE
Feature Request: Supervised Feature Selection

### ISSUE THREAD

**Issue by kylegilde** [tidymodels/recipes#504]
At some point, it would be nice to see some supervised feature selection steps, like Lasso or recursive feature elimination. 

Thank you!

**Comment by EmilHvitfeldt** [comment]
It sounds like a good idea. It will most likely go into a add-on package such as [textrecipes](https://github.com/tidymodels/textrecipes), [embed](https://github.com/tidymodels/embed/) and [themis](https://github.com/tidymodels/themis).

**Comment by topepo** [comment]
[This repo](https://github.com/stevenpawley/recipeselectors) looks like a good start ( @stevenpawley ). 

See [my comments](https://github.com/stevenpawley/recipeselectors/issues/1) on my more strategic thoughts about where they belong. 

More complex selection algorithms might need to be implemented outside of recipes because they can't be done from steps (or might be really inefficient within recipes).
