### ISSUE TITLE
Reverse BoxCox transformation on target variable

### ISSUE THREAD

**Issue by anks7190** [tidymodels/recipes#562]
Hi , 

I have applied BoxCox transformation  on the target variable using step_BoxCox(numeric_target_var) .
So after prediction , how can I reverse boxcox transformation so as to make sense of the predicted value. 

Thanks

**Comment by topepo** [comment]
We'll be working on how to do that (probably using the `workflows` package). You couldn't do it in `recipes` since this happens prior to modeling. You can use the `tidy()` method for the step to get the transformation value though. 

 _However_, we do strongly suggest that computations on the outcome be done outside of a recipe since the outcome is usually not present when the recipe is baked on new data (including a test set).
