### ISSUE TITLE
Integrate arbitrary pre-processing function into a recipe

### ISSUE THREAD

**Issue by lorenzwalthert** [tidymodels/recipes#576]
One great advantage of the `{workflows}` package is - obviously - that model and pre-processing can be bundled. For arbitrary pre-processing of columns, I can use `recipes::step_mutate()`, `recipes::step_filter()` etc., although this approach is a bit limiting (I can't use arbitrary R code). However, if I have one pre-processing function `f()` that takes my datatframe (and not just a column vector of it) and that does not estimate anything and really just performs data cleaning, it would be handy if I could integrate such a function into a recipe. Otherwise, I have to carry that function along (similar to what I'd to do with a recipe if I would not use `{workflows}`). In particular, if such a function manipulates `data` with pure dplyr code, we can leverage dbplyr to execute the code also on a database, which is not possible if we use `{recipes}` functions like `recipes::step_mutate()`. So from a point of portability and flexibility, it would be desirable to do something like:
```r
basic_cleaning <- function(data) {
  # arbitrary data transformation
}
library(recipes)
rec(...) %>%
  step_lambda(basic_cleaning)
```

I am aware that this has the potential to be misused, namely if the function contains transformations that modify the input data depending on the input data. This had to be made very clear in the documentation in case you want to support this feature. However, the problem already exists with `step_mutate()`, e.g. when I use `step_mutate(z = (x - mean(x))/sd(x))` to standardise my variable instead of using `recipes::step_normalize()` I leak information from the test data set when used for inference. For this reason, in any case, I think the docs of `step_mutate()` should contain a warning.

**Comment by juliasilge** [comment]
We recommend that most data cleaning takes place outside of a recipe, because of issues around what to do when you have new data (like the testing data or new data at prediction time). You can read more about this here at ["Skipping Steps for New Data"](https://www.tmwr.org/recipes.html#skip-equals-true):

> In fact, to avoid _information leakage_, many tidymodels packages isolate the data being used when making any predictions.

You may find that you run into failures during tuning or at prediction time if you use `step_mutate()` and `step_filter()` for a lot of arbitrary data cleaning tasks without careful planning. It is typically better to implement simple transformations outside of a recipe; recipes are best for statistical transformations that need to be estimated from training data.

If you want to write a function to do both data cleaning and data preprocessing for modeling, try out an approach like this:

```r
clean_and_preprocess <- function(data) {
    data <- basic_cleaning(data)
    recipe(data) %>%
       step_xxx(var1) %>%
       step_yyy(var2)
}
```

**Comment by lorenzwalthert** [comment]
Thanks @juliasilge for the detailed answer.

**Comment by topepo** [comment]
I agree with @juliasilge about where data cleaning should happen.

My other thoughts: not a bad idea to have a general function for doing stuff in a recipe but, since sooo many things could go wrong, I would not want to support it.
