### ISSUE TITLE
Would it be possible to parallelize the imputation steps such as step_bagimpute? 

### ISSUE THREAD

**Issue by UnclAlDeveloper** [tidymodels/recipes#599]
I am mostly requesting this for step_bagimpute, but I think it could possibly apply to step_knnimpute.  Would it be possible to add a parallel option to this step, as for moderate sized datasets, step_bagimpute can take hours or days to train as it only runs on a single processor?

**Comment by juliasilge** [comment]
Related to #323, #519, and originally #48.

You can already pass options to `gower::gower_topn()` for threading for `step_knnimpute()`. We are not likely to parallelize `step_bagimpute()` or other similar steps in the very near term because of the challenges with parallelization for recipes laid out in these issues. I'm going to close this issue since we are tracking interest in #48. Please feel free to add any new thoughts there or ➕ anything you agree with!
