### ISSUE TITLE
parallelizing step_corr

### ISSUE THREAD

**Issue by kylegilde** [tidymodels/recipes#642]
Hello!

I was wondering if anyone has considered providing a function parameter that allows the user to calculate the correlations using multiple threads.

I'm finding that this step is taking a very long time to run when I'm using it with a few hundred features and a couple of million rows.

Thank you!

**Comment by juliasilge** [comment]
Thank you for your feedback @kylegilde! 🙌 This is related to #48 originally, #323, #519, and #599.

We are not likely to parallelize preprocessing steps in the very near term because of the challenges with parallelization for recipes laid out in those issues (i.e. preferring to prioritize support for parallelization over resamples instead of parallelization within a single operation for statistical reasons). I'm going to close this issue since we are tracking interest in #48 but please feel free to add any new thoughts in that thread or ➕ anything you agree with!
