### ISSUE TITLE
step_novel does not work properly with factors

### ISSUE THREAD

**Issue by jjcurtin** [tidymodels/recipes#656]
I recognize that this was raised as an issue (#627) and that in that example, the use of step_nzv() undid the effects of step_novel().    However, the solution provided by Julia simply demonstrated that step_nzv() should not be used after step_novel().  It did not address a more fundamental problem (at least it seems to me) with the use of step_novel() when a character variable is first transformed into a factor.   I am including the example from the documentation on step_novel() with one modification to demonstrate this issue.  I simply add step_string2factor() for diet before using step_novel() on diet.   This appears to result in the new levels of diet in test now set to NA rather than "new".   Am I missing something here?

library(dplyr)
library(recipes)
library(modeldata)

data(okc)

okc_tr <- okc[1:30000,]
okc_te <- okc[30001:30006,]
okc_te$diet[3] <- "cannibalism"
okc_te$diet[4] <- "vampirism"

rec <- recipe(~ diet, data = okc_tr) %>% 
  step_string2factor(diet) %>% 
  step_novel(diet)

rec <- prep(rec, training = okc_tr)

processed <- bake(rec, okc_te)
tibble(old = okc_te$diet, new = processed$diet)

Of course, this same code works fine if I simply remove step_string2factor() from the recipe

rec_2 <- recipe(~ diet, data = okc_tr) %>% 
  step_novel(diet)
rec_2 <- prep(rec_2, training = okc_tr)

processed_2 <- bake(rec_2, okc_te)
tibble(old = okc_te$diet, new = processed_2$diet)

**Comment by juliasilge** [comment]
This is very similar to the confusion faced in #494, where it was `step_unknown()` that doesn't do what is expected _after_ `step_novel()` but is fine before. This happens because steps like `step_unknown()` and `step_string2factor()` don't really have any choice but to set the factor levels using the levels in the `object` already, slurping up what came from the step before. The factor levels are then **set** and there are no new levels anymore to deal with.

In this case you again want to do `step_novel()` first, so it can see the new factor levels before other steps start messing with them:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(recipes)
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

data(okc, package = "modeldata")

okc_tr <- okc[1:30000,]
okc_te <- okc[30001:30006,]
okc_te$diet[3] <- "cannibalism"
okc_te$diet[4] <- "vampirism"

rec <- recipe(~ diet, data = okc_tr) %>%
  step_novel(diet) %>%
  step_string2factor(diet)

rec <- prep(rec, training = okc_tr)

processed <- bake(rec, okc_te)
tibble(old = okc_te$diet, new = processed$diet)
#> # A tibble: 6 x 2
#>   old               new              
#>   <chr>             <fct>            
#> 1 vegetarian        vegetarian       
#> 2 strictly anything strictly anything
#> 3 cannibalism       new              
#> 4 vampirism         new              
#> 5 <NA>              <NA>             
#> 6 <NA>              <NA>
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

This is a little silly of course, because now `step_string2factor()` isn't doing anything since `step_novel()` will also make factors.

I definitely think we need to [add to this article about ordering steps](https://recipes.tidymodels.org/articles/Ordering.html) with advice on factor handling as discussed also in #641.

🎯 Do we want to add another warning for `step_string2factor()`, similar to the one added in #612 for `step_unknown()`? The need is not as obvious to me.

**Comment by jjcurtin** [comment]
If the end user perspective is helpful, here was/is what confused me.  After reading the help on `step_novel()` I noted that it worked with variables that could be either character or factor.  I also checked that if diet was already a factor in the raw data, `step_novel()` worked as expected.  Therefore, its not clear to me why `step_novel()` does not work when diet was a character type in the raw data but converted to a factor by an earlier step in the recipe by `step_string2factor()` .   I assumed that `step_novel()` would not have trouble changing the factor levels for diet to include "new",  regardless of when diet had been converted to factor (inside or outside the recipe).   Big thanks for all your work on this!
