### ISSUE TITLE
`step_modeimpute` returns all NA when column is completely null, instead of mode from training data

### ISSUE THREAD

**Issue by jake-mason** [tidymodels/recipes#689]
I'm not sure if this is intended behavior, or if I'm missing some other step that could help me to avoid this issue, but when using a recipe with `step_modeimpute` (this may also apply to other steps – didn't verify) on a factor column, when the column in `new_data` is completely NA, NAs are returned, as opposed to the mode from the training dataset.

```R
df <- data.frame(x = as.factor(c(0, 1, 0)))
binary_features <- 'x'

base_recipe <- recipes::recipe(df) %>%
	update_role(all_of(binary_features), new_role = 'predictor') %>%
	# Impute mode for binary features
	step_modeimpute(one_of(binary_features))

prepped_recipe <- prep(
	base_recipe,
	training = df,
	strings_as_factors = FALSE,
	retain = FALSE,
	fresh = TRUE
)
```

Let's try it out:

```
# Our original data.frame – looks good!
> bake(prepped_recipe, new_data = df)
# A tibble: 3 x 1
  x    
  <fct>
1 0    
2 1    
3 0    
# A new data.frame, with NA, 1, and 0 present. Still looks good – the mode is imputed.
> bake(prepped_recipe, new_data = data.frame(x = as.factor(c(NA, NA, 1, 0))))
# A tibble: 4 x 1
  x    
  <fct>
1 0    
2 0    
3 1    
4 0    
# Another data.frame, this time completely NA. No mode imputed.
> bake(prepped_recipe, new_data = data.frame(x = as.factor(c(NA, NA))))
# A tibble: 2 x 1
  x    
  <fct>
1 NA   
2 NA   
```

This behavior seems strange to me, but then again maybe I'm missing something and there's good reason for this.

**Comment by juliasilge** [comment]
This is happening because of how `recipes:::cast()` works:

``` r
recipes:::cast("0", as.factor(c(NA, NA, 1, 0)))
#> [1] 0
#> Levels: 0 1
recipes:::cast("0", as.factor(c(NA, NA)))
#> [1] <NA>
#> Levels:
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DavisVaughan** [comment]
So I took a closer look at this. I think the problem is not necessarily with `cast()`, but with the data that we are passing to `cast()`. This is a case where:

- At training time we have a factor with a set of levels
- At test time we have a factor with a _different_ set of levels

Note that if the all `NA` column was carefully created to have the right levels, then there wouldn't be any issues:

``` r
library(recipes)

df <- data.frame(x = as.factor(c(0, 1, 0)))

base_recipe <- recipes::recipe(df) %>%
  update_role(x, new_role = 'predictor') %>%
  step_impute_mode(x)

prepped_recipe <- prep(
  base_recipe,
  training = df,
  strings_as_factors = FALSE,
  retain = FALSE,
  fresh = TRUE
)

bake(prepped_recipe, new_data = data.frame(x = factor(c(NA, NA))))
#> # A tibble: 2 x 1
#>   x    
#>   <fct>
#> 1 <NA> 
#> 2 <NA>

bake(prepped_recipe, new_data = data.frame(x = factor(c(NA, NA), levels = c("0", "1"))))
#> # A tibble: 2 x 1
#>   x    
#>   <fct>
#> 1 0    
#> 2 0
```

`cast()` is doing what it is supposed to do, it is using the levels of the reference input to create the factor. It just happens that the reference input has no levels because the input is all NAs.

I _think_ the right thing to do is to capture the ptype or levels of the training set at `prep()` time, and then ensure that either:
- The test data also has those same factor levels, or we error
- Or we try to force the test data to have those factor levels if it doesn't already (one way to do this is with `hardhat::scream()`)

Once we check or fix up the factor levels, the way we are using `cast()` should work fine.

It would also be worth looking at other imputation steps, they might have a similar issue

**Comment by juliasilge** [comment]
I'm pretty sure this affects all the imputation steps, because of how `cast()` is behaving:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

df <- data.frame(x = c(0, 1, 0))

base_recipe <- recipes::recipe(df) %>%
  update_role(x, new_role = 'predictor') %>%
  step_impute_median(x)

prepped_recipe <- prep(
  base_recipe,
  training = df,
  strings_as_factors = FALSE,
  retain = FALSE,
  fresh = TRUE
)

bake(prepped_recipe, new_data = data.frame(x = c(NA, NA, 1, 0)))
#> # A tibble: 4 x 1
#>       x
#>   <dbl>
#> 1     0
#> 2     0
#> 3     1
#> 4     0
bake(prepped_recipe, new_data = data.frame(x = c(NA, NA)))
#> # A tibble: 2 x 1
#>   x    
#>   <lgl>
#> 1 FALSE
#> 2 FALSE
```

<sup>Created on 2021-04-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

recipes doesn't currently use hardhat; do you think it would be a problem to start importing it @DavisVaughan?

**Comment by DavisVaughan** [comment]
I think that would be fine
