### ISSUE TITLE
new feature hashing step

### ISSUE THREAD

**Issue by topepo** [tidymodels/recipes#710]
`embed` has a step to do this but it required tensorflow. We should create an additional step that uses `rlang::hash()` .

**Comment by EmilHvitfeldt** [comment]
two things

the hash is not guaranteed to work across R versions. 

> The generated hash is guaranteed to be reproducible across platforms, but not across R versions.

> On R >= 3.5.0, serialization version 3 is used, otherwise version 2 is used.

I think this is fine since we are only testing 3.6.0 and forward.

Secondly, what do we name this step? embed as [step_feature_hash()](https://embed.tidymodels.org/reference/step_feature_hash.html) and textrecipes has [step_texthash()](https://textrecipes.tidymodels.org/reference/step_texthash.html) which does something similar.
