### ISSUE TITLE
Include library(recipes) in examples

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/recipes#767]
If you press the copy button of the example of a recipe, you don't get a runnable piece of code since it is assumed that {recipes} is loaded.

This feels like it would be an easy fix (unless there is some CRAN check that complains)

<img width="866" alt="Screen Shot 2021-08-15 at 4 28 17 PM" src="https://user-images.githubusercontent.com/14034784/129495863-38ddd94f-ce31-415b-9ae9-803b3323ff91.png">
<img width="810" alt="Screen Shot 2021-08-15 at 4 28 40 PM" src="https://user-images.githubusercontent.com/14034784/129495864-bc82a15c-c635-4cd0-a421-abacb3da7e16.png">

**Comment by DavisVaughan** [comment]
I think our general stance in all packages across the tidyverse is that the Examples sections for {foo} are allowed to assume that the user has {foo} loaded. I think that is a reasonable assumption, and in the somewhat rare cases where you don't have the package loaded, I'm optimistic that it is easy to figure out what the issue is

**Comment by EmilHvitfeldt** [comment]
Okay, that seems like a reasonable assumption.
