### ISSUE TITLE
STEP FUNCTIONS - IMPUTATION is missing some imputations in the reference page

### ISSUE THREAD

**Issue by DesmondChoy** [tidymodels/recipes#780]
[STEP FUNCTIONS -IMPUTATION](https://recipes.tidymodels.org/reference/index.html#:~:text=Manually%20Alter%20Roles-,STEP%20FUNCTIONS%20-%20IMPUTATION,-step_impute_linear()) in the recipes reference page is missing some imputations like `step_impute_knn`

I can still view it [here](https://recipes.tidymodels.org/reference/step_impute_knn.html) after googling for it, but it's missing from the reference page.

**Comment by EmilHvitfeldt** [comment]
The reference got fixed in https://github.com/tidymodels/recipes/pull/753, but the change is still in the developmental version. You can see the documentation of the dev version by putting `dev/` after `https://recipes.tidymodels.org/` like so:

https://recipes.tidymodels.org/dev/reference/index.html#section-step-functions-imputation
