### ISSUE TITLE
`step_kpca()` missing from the Reference section of the website

### ISSUE THREAD

**Issue by mmp3** [tidymodels/recipes#815]
Minor documentation oversight:

`step_kpca()` is missing from the [_Reference_ section](https://recipes.tidymodels.org/reference/index.html) of the recipes website.

**Comment by hfrick** [comment]
Thanks for reporting this, @mmp3 ! `step_kpca()` is not shown on the release version of the website because it is deprecated in that release. 

In the development version we have reversed that decision and thus also include it in the website again. You can find the website for the development version of recipes at https://recipes.tidymodels.org/dev/.

**Comment by juliasilge** [comment]
Let us know if you have further questions @mmp3!
