### ISSUE TITLE
rowwise steps

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/recipes#949]
Is there a way to apply `step_mutate` rowwise?

**Comment by juliasilge** [comment]
Can you say a little more about what you want to do @nipnipj? Perhaps with a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example)? The goal of a reprex is to make it easier for us to recreate what you are thinking about so that we can understand it and/or suggest a solution.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by nipnipj** [comment]
Thank you for replying.
I was thinking on something like this
```
tb <- tibble(c1 = rnorm(10),
             c2 = rnorm(10, 2),
             c3 = rnorm(10, 3))

tb %>% 
  rowwise() %>% 
  mutate(sd = sd(across(starts_with("c")))) 
```
But within `recipes` package.

**Comment by EmilHvitfeldt** [comment]
I have actually been thinking about a step like this or a little bit. Calculating summary statistics across variables can be nice if the data is particularly wide (sales in different districts each having a columns by itself).

The interface I had imagined would be something like

```r
recipe(~., data = tb) %>%
  step_nameofstep(starts_with("c"), fn = list(sd = sd))
```

If we don't think it fits in {recipes} I would be happy to include it in https://github.com/EmilHvitfeldt/extrasteps.

**Comment by EmilHvitfeldt** [comment]
I like this step. I'm going  close this issue in favor for this issue here: https://github.com/EmilHvitfeldt/extrasteps/issues/55
